name: acceptance
on: [push, pull_request]
jobs:
  acceptance:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '~1.15'
          - '~1.16'
          - '~1.17'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test -race -v ./...
